### ISSUE TITLE
Adicionar requirements para o projeto

### ISSUE THREAD

**Issue by PedroRegisPOAR** [maurochiozzi/grid-plantio-py#1]
Para facilitar (ou até não impossibilitar) que outras pessoas possam contribuir com o projeto deve-se adicionar um arquivo de requerimentos do projeto com o nome padrão `requirements.txt`. Isto facilita a mantenabilidade do projeto e possibilita que outras pessoas possam contribuir com muito mais facilidade. 

**Extra.** Atualmente alguns projetos já utilizam [pipenv](https://pipenv.readthedocs.io/en/latest/), no futuro provavélmente este será o padrão do python, ou seja, não se utilizará o `requirements.txt`, mas sim os arquivos `Pipfile` e `Pipfile.lock`, [se estiver curioso olhe esse exemplo](https://pipenv.readthedocs.io/en/latest/basics/#example-pipfile-pipfile-lock). Postagens que explicam o pq de usar existem aos montes, [essa](https://realpython.com/pipenv-guide/) explica inclusive com exemplos de Django.

Basta fazer no terminal:

`$ pip freeze > requirements.txt`

Note: cuidado para não inserir dependências desnecessarias. Vc deveria esta usando algum gerenciador de ambientes para não instalar globalmente as coisas. Alguns exemplos são: [virtualenv](https://docs.python.org/3/library/venv.html), [conda](https://conda.io/en/latest/), [miniconda](https://conda.io/en/latest/miniconda.html), e  também o [Docker](https://www.docker.com/) (meu preferido por poder lidar com qualquer tipo de dependência). 

No Linux vc pode usar o venv assim:

```console
root@db19ca78f65c:/home# python3 -m venv escolha_um_nome
root@db19ca78f65c:/home# cd escolha_um_nome/
root@db19ca78f65c:/home/escolha_um_nome# source bin/activate
(escolha_um_nome) root@db19ca78f65c:/home/escolha_um_nome# ls
bin  include  lib  lib64  pyvenv.cfg
(escolha_um_nome) root@db19ca78f65c:/home/escolha_um_nome# deactivate
root@db19ca78f65c:/home/escolha_um_nome# 
```

Pelo que lembro no Windows é bem parecido.

Dentro desse ambiente vc pode rodar o pip install -r requirements.txt e instalar todas as suas dependências. Note que inicialmente a instalação será manual, por exemplo `pip install django` ai depois disso vc roda o `pip freeze > requirements.txt`.

Mais explicações sobre o que é o requirements e sobre o `pip freeze > requirements.txt`, no link:
https://pip.pypa.io/en/stable/user_guide/

**Comment by maurochiozzi** [comment]
Requirements.txt adicionado.
